# Solution to Project Euler problem 29 - https://projecteuler.net/problem=29
# How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

# returns the number of distinct powers results, in the from a^b where 2 <= a <= aLimit and 2 <= b <= bLimit
def distinctPowers(aLimit,bLimit):
    count = 0
    #use a mask array of size aLimit ^ blimit (ie the upper range we will be calculating) to track previous results so they are not counted again
    #resultMask = [0] * ((aLimit**bLimit) +1)
    resultList = []
    # loop through a and b counting the unique values
    for a in range(2, aLimit+1):
        for b in range(2, bLimit+1):
            currentValue = a ** b
            #if(resultMask[currentValue] == 0):
            #    resultMask[currentValue] = 1
            if(currentValue not in resultList):
                resultList.append(currentValue)
                count += 1  
    return count